import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import CustomerNavbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "wak-web",
  description: "Generated by wak-web",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const userMode = cookieStore.get("user-mode")?.value || "customer";

  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >

      <body className="min-h-full flex flex-col mx-auto font-sans">
        <CustomerNavbar userMode={userMode} />
        <div className="">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
